// Stable starter identifiers, retained while the registry grows.
export const coreSkills: [string, string, string[]][] = [
  ['typescript', 'TypeScript', ['TypeScript']],
  ['javascript', 'JavaScript', ['JavaScript', 'ECMAScript']],
  ['java', 'Java', ['Java']],
  ['kotlin', 'Kotlin', ['Kotlin']],
  ['python', 'Python', ['Python']],
  ['golang', 'Go', ['Golang', 'Go']],
  ['rust', 'Rust', ['Rust']],
  ['csharp', 'C#', ['C#', 'C Sharp']],
  ['cpp', 'C++', ['C++']],
  ['react', 'React', ['React.js', 'ReactJS', 'React']],
  ['angular', 'Angular', ['Angular']],
  ['vue', 'Vue', ['Vue.js', 'VueJS']],
  ['nodejs', 'Node.js', ['Node.js', 'NodeJS']],
  ['html', 'HTML', ['HTML', 'HTML5']],
  ['css', 'CSS', ['CSS', 'CSS3']],
  ['sql', 'SQL', ['SQL']],
  ['postgresql', 'PostgreSQL', ['PostgreSQL', 'Postgres']],
  ['mysql', 'MySQL', ['MySQL']],
  ['mongodb', 'MongoDB', ['MongoDB']],
  ['redis', 'Redis', ['Redis']],
  ['graphql', 'GraphQL', ['GraphQL']],
  ['rest', 'REST APIs', ['REST API', 'REST APIs', 'RESTful']],
  ['git', 'Git', ['Git']],
  ['docker', 'Docker', ['Docker']],
  ['kubernetes', 'Kubernetes', ['Kubernetes', 'K8s']],
  ['aws', 'AWS', ['AWS', 'Amazon Web Services']],
  ['azure', 'Azure', ['Azure']],
  ['gcp', 'Google Cloud', ['Google Cloud', 'GCP']],
  ['terraform', 'Terraform', ['Terraform']],
  ['linux', 'Linux', ['Linux']],
  ['ci-cd', 'CI/CD', ['CI/CD', 'continuous integration']],
  ['machine-learning', 'Machine learning', ['machine learning']],
  ['pytorch', 'PyTorch', ['PyTorch']],
  ['tensorflow', 'TensorFlow', ['TensorFlow']],
  ['pandas', 'pandas', ['pandas']],
  ['spark', 'Apache Spark', ['Apache Spark', 'PySpark', 'Spark']],
  ['excel', 'Excel', ['Excel']],
  ['tableau', 'Tableau', ['Tableau']],
  ['power-bi', 'Power BI', ['Power BI']],
  ['figma', 'Figma', ['Figma']],
  ['user-research', 'User research', ['user research']],
  ['product-discovery', 'Product discovery', ['product discovery']],
  ['roadmapping', 'Product roadmapping', ['roadmapping', 'product roadmap']],
  ['ab-testing', 'A/B testing', ['A/B testing', 'A/B tests']],
  ['scrum', 'Scrum', ['Scrum']],
  ['salesforce', 'Salesforce', ['Salesforce']],
  ['hubspot', 'HubSpot', ['HubSpot']],
  ['account-management', 'Account management', ['account management']],
  ['recruiting', 'Recruiting', ['recruiting', 'recruitment']],
  ['talent-acquisition', 'Talent acquisition', ['talent acquisition']],
  ['payroll', 'Payroll', ['payroll']],
  ['financial-modeling', 'Financial modeling', ['financial modeling', 'financial modelling']],
  ['dbt', 'dbt', ['dbt']],
  ['statistics', 'Statistics', ['statistics', 'statistical analysis']],
  ['sales-prospecting', 'Sales prospecting', ['prospecting', 'lead generation']],
  ['negotiation', 'Negotiation', ['negotiation', 'negotiating']],
  ['hris', 'HRIS', ['HRIS']],
  ['employee-relations', 'Employee relations', ['employee relations']],
  ['product-strategy', 'Product strategy', ['product strategy']],
  [
    'distributed-systems',
    'Distributed systems',
    ['distributed systems', 'distributed services', 'distributed computing'],
  ],
  ['microservices', 'Microservices', ['microservices', 'microservice']],
  ['cloud-infrastructure', 'Cloud infrastructure', ['cloud infrastructure', 'cloud computing']],
  [
    'cloud-applications',
    'Cloud applications',
    ['cloud applications', 'cloud-based applications', 'cloud-native applications'],
  ],
  [
    'operating-systems',
    'Operating systems',
    ['operating systems', 'operating system', 'OS concepts'],
  ],
  ['low-level', 'Low-level programming', ['low-level', 'low level programming', 'low level']],
  ['memory-management', 'Memory management', ['memory management']],
  ['multithreading', 'Multithreading', ['multithreading', 'multi-threading', 'multi threading']],
  ['concurrency', 'Concurrency', ['concurrency', 'concurrent programming']],
  ['systems-programming', 'Systems programming', ['systems programming']],
  ['networking', 'Networking', ['computer networking', 'networking']],
  ['storage', 'Storage systems', ['storage systems', 'distributed storage']],
  ['caching', 'Caching', ['caching', 'distributed cache']],
  [
    'fault-tolerance',
    'Fault tolerance',
    ['fault-tolerance', 'fault tolerance', 'fault-tolerant', 'fault tolerant'],
  ],
  ['high-availability', 'High availability', ['high availability', 'high-availability']],
  [
    'performance-optimization',
    'Performance optimization',
    ['performance optimization', 'performance optimisation'],
  ],
  [
    'performance-benchmarking',
    'Performance benchmarking',
    ['performance benchmarking', 'performance benchmarks'],
  ],
  ['low-latency', 'Low latency', ['low latency', 'low-latency']],
  [
    'scalability',
    'Scalability',
    ['scalability', 'scalable', 'large scale systems', 'large-scale systems'],
  ],
  ['data-structures', 'Data structures', ['data structures']],
  ['algorithms', 'Algorithms', ['algorithms']],
  ['kafka', 'Apache Kafka', ['Apache Kafka', 'Kafka']],
  ['rabbitmq', 'RabbitMQ', ['RabbitMQ']],
  ['dynamodb', 'DynamoDB', ['DynamoDB']],
  ['grpc', 'gRPC', ['gRPC']],
  ['observability', 'Observability', ['observability']],
];

export const coreCompetencies: [string, string, string[]][] = [
  [
    'leadership',
    'Team leadership',
    ['team leadership', 'people management', 'leading a group of', 'leading a team'],
  ],
  ['mentoring', 'Mentoring', ['mentoring', 'mentorship']],
  [
    'stakeholder-communication',
    'Stakeholder communication',
    ['stakeholder communication', 'stakeholder management'],
  ],
  ['delivery-ownership', 'Delivery ownership', ['delivery ownership', 'project ownership']],
  [
    'cross-functional-leadership',
    'Cross-functional leadership',
    [
      'cross-functional leadership',
      'cross functional leadership',
      'lead cross-functional initiatives',
      'leading cross-functional initiatives',
      'led cross-functional initiatives',
    ],
  ],
];
