import type { ConceptKind } from './model.js';

// Reviewed against public employer descriptions. Frequency proposes candidates; it never
// establishes proficiency, requirement importance or relationships between concepts.
export const corpusPacks: {
  kind: ConceptKind;
  family: string;
  entries: [string, string, string[]][];
}[] = [
  {
    kind: 'language',
    family: 'application-development',
    entries: [
      ['ruby', 'Ruby', []],
      ['swift', 'Swift', []],
      ['objective-c', 'Objective-C', []],
      ['r', 'R', ['R programming', 'R language']],
      ['bash', 'Bash', []],
      ['powershell', 'PowerShell', []],
      ['perl', 'Perl', []],
      ['tcl', 'Tcl', []],
      ['verilog', 'Verilog', []],
      ['systemverilog', 'SystemVerilog', ['System Verilog']],
      ['vhdl', 'VHDL', []],
    ],
  },
  {
    kind: 'tool',
    family: 'application-development',
    entries: [
      ['spring', 'Spring Framework', ['Spring']],
      ['spring-boot', 'Spring Boot', []],
      ['hibernate', 'Hibernate ORM', ['Hibernate']],
      ['django', 'Django', []],
      ['flask', 'Flask', []],
      ['fastapi', 'FastAPI', []],
      ['rails', 'Ruby on Rails', ['Rails']],
      ['dotnet', '.NET', ['dotnet', '.NET Core']],
      ['aspnet', 'ASP.NET', ['ASP.NET Core']],
      ['nextjs', 'Next.js', ['NextJS']],
      ['svelte', 'Svelte', []],
      ['react-native', 'React Native', []],
      ['flutter', 'Flutter', []],
      ['jquery', 'jQuery', []],
      ['tailwind', 'Tailwind CSS', ['Tailwind']],
      ['webpack', 'Webpack', []],
      ['vite', 'Vite', []],
      ['junit', 'JUnit', []],
      ['mockito', 'Mockito', []],
      ['pytest', 'pytest', []],
      ['jest', 'Jest', []],
      ['vitest', 'Vitest', []],
      ['cypress', 'Cypress', []],
      ['playwright', 'Playwright', []],
      ['espresso', 'Espresso', ['Android Espresso']],
      ['xcuitest', 'XCUITest', ['XCUI Test']],
      ['selenium', 'Selenium', []],
      ['postman', 'Postman', []],
      ['perforce', 'Perforce', []],
      ['uvm', 'Universal Verification Methodology', ['UVM']],
      ['nix', 'Nix', []],
      ['packer', 'Packer', []],
      ['chef', 'Chef Infra', ['Chef']],
      ['puppet', 'Puppet', []],
      ['splunk', 'Splunk', []],
      ['sentry', 'Sentry', []],
      ['spice-simulation', 'SPICE simulation', ['SPICE simulator']],
      ['hspice', 'HSPICE', []],
      ['rocm', 'ROCm', []],
      ['nccl', 'NCCL', []],
      ['opencl', 'OpenCL', []],
    ],
  },
  {
    kind: 'tool',
    family: 'data-ai',
    entries: [
      ['snowflake', 'Snowflake', []],
      ['hadoop', 'Apache Hadoop', ['Hadoop']],
      ['hive', 'Apache Hive', ['Hive']],
      ['trino', 'Trino', []],
      ['presto', 'Presto', []],
      ['iceberg', 'Apache Iceberg', ['Iceberg', 'PyIceberg']],
      ['delta-lake', 'Delta Lake', []],
      ['debezium', 'Debezium', []],
      ['fivetran', 'Fivetran', []],
      ['airbyte', 'Airbyte', []],
      ['dagster', 'Dagster', []],
      ['looker', 'Looker', []],
      ['matlab', 'MATLAB', []],
      ['numpy', 'NumPy', []],
      ['scipy', 'SciPy', []],
      ['scikit-learn', 'scikit-learn', ['sklearn', 'scikit learn']],
      ['xgboost', 'XGBoost', []],
      ['lightgbm', 'LightGBM', []],
      ['jax', 'JAX', []],
      ['keras', 'Keras', []],
      ['mlflow', 'MLflow', []],
      ['kubeflow', 'Kubeflow', []],
      ['tensorrt', 'TensorRT', []],
      ['onnx-runtime', 'ONNX Runtime', []],
      ['vllm', 'vLLM', []],
      ['sglang', 'SGLang', []],
      ['langchain', 'LangChain', []],
      ['langgraph', 'LangGraph', []],
      ['llamaindex', 'LlamaIndex', []],
      ['ray', 'Ray', []],
      ['opencv', 'OpenCV', []],
      ['jupyter', 'Jupyter', ['Jupyter notebooks']],
      ['pinecone', 'Pinecone', []],
      ['weaviate', 'Weaviate', []],
      ['qdrant', 'Qdrant', []],
      ['pgvector', 'pgvector', []],
      ['unity-catalog', 'Unity Catalog', []],
      ['mariadb', 'MariaDB', []],
      ['neo4j', 'Neo4j', []],
      ['polars', 'Polars', []],
      ['dask', 'Dask', []],
      ['knime', 'KNIME', []],
      ['alteryx', 'Alteryx', []],
      ['sas', 'SAS analytics', ['SAS']],
      ['stata', 'Stata', []],
      ['oracle-database', 'Oracle Database', ['Oracle RDBMS', 'Oracle']],
    ],
  },
  {
    kind: 'platform',
    family: 'cloud',
    entries: [
      ['gcp-storage', 'Google Cloud Storage', ['GCS']],
      ['aws-redshift', 'Amazon Redshift', ['AWS Redshift', 'Redshift']],
      ['aws-glue', 'AWS Glue', ['Amazon Glue']],
      ['aws-cloudwatch', 'Amazon CloudWatch', ['CloudWatch', 'AWS CloudWatch']],
      ['gcp-vertex', 'Vertex AI', ['Google Vertex AI']],
      ['gcp-cloud-run', 'Cloud Run', ['Google Cloud Run']],
      ['gcp-dataproc', 'Dataproc', ['Google Dataproc']],
      ['azure-devops', 'Azure DevOps', []],
      ['azure-data-factory', 'Azure Data Factory', []],
      ['azure-synapse', 'Azure Synapse', ['Azure Synapse Analytics']],
    ],
  },
  {
    kind: 'capability',
    family: 'data-ai',
    entries: [
      ['parquet', 'Apache Parquet', ['Parquet']],
      ['avro', 'Apache Avro', ['Avro']],
      ['protobuf', 'Protocol Buffers', ['Protobuf']],
      ['onnx', 'ONNX', []],
      ['data-analysis', 'Data analysis', []],
      ['data-warehousing', 'Data warehousing', ['data warehouse', 'data warehouses']],
      ['data-lakes', 'Data lakes', ['data lake', 'lakehouse architectures']],
      ['change-data-capture', 'Change data capture', ['log-based CDC']],
      ['schema-evolution', 'Schema evolution', []],
      ['data-integration', 'Data integration', ['datastore integration']],
      ['deep-learning', 'Deep learning', []],
      ['nlp', 'Natural language processing', ['NLP']],
      ['computer-vision', 'Computer vision', []],
      ['reinforcement-learning', 'Reinforcement learning', []],
      ['causal-inference', 'Causal inference', []],
      ['experimental-design', 'Experimental design', ['design of experiments']],
      ['statistical-modeling', 'Statistical modeling', ['statistical modelling']],
      ['predictive-modeling', 'Predictive modeling', ['predictive modelling']],
      ['llm', 'Large language models', ['large language model', 'LLMs', 'LLM']],
      ['rag', 'Retrieval-augmented generation', ['retrieval augmented generation', 'RAG']],
      ['model-fine-tuning', 'Model fine-tuning', ['LLM fine-tuning', 'fine-tuning models']],
      ['feature-stores', 'Feature stores', ['feature store']],
      ['vector-search', 'Vector search', ['vector databases', 'vector database']],
      ['information-retrieval', 'Information retrieval', []],
      ['recommender-systems', 'Recommender systems', ['recommendation systems']],
      ['time-series-analysis', 'Time-series analysis', ['time series analysis']],
      ['mlops', 'MLOps', []],
      ['distributed-training', 'Distributed training', []],
      ['quantization', 'Model quantization', ['model quantisation']],
    ],
  },
  {
    kind: 'capability',
    family: 'engineering-practices',
    entries: [
      [
        'technical-documentation',
        'Technical documentation',
        ['API documentation', 'developer documentation', 'documentation'],
      ],
      [
        'dead-letter-queues',
        'Dead-letter queues',
        ['dead letter queues', 'dead-letter queue', 'dead letter queue'],
      ],
      [
        'automated-provisioning',
        'Automated provisioning',
        ['automatic provisioning', 'infrastructure provisioning'],
      ],
      ['safe-defaults', 'Safe defaults', []],
      ['infrastructure-as-code', 'Infrastructure as code', ['Infrastructure-as-Code', 'IaC']],
      ['test-automation', 'Test automation', ['automated testing', 'automated tests']],
      ['software-testing', 'Software testing', ['software tests', 'testing concepts', 'testing']],
      ['testing-pyramid', 'Testing pyramid', ['test pyramid']],
      [
        'test-quality',
        'Test quality',
        ['flaky test rate', 'test coverage', 'suite execution time'],
      ],
      ['code-review', 'Code review', ['code reviews']],
      ['site-reliability', 'Site reliability engineering', ['site reliability', 'SRE practices']],
      ['embedded-systems', 'Embedded systems', ['embedded software']],
      ['firmware-development', 'Firmware development', ['firmware engineering']],
      ['rtl-design', 'RTL design', ['RTL coding', 'register-transfer level design']],
      ['asic-design', 'ASIC design', ['ASIC development']],
      ['fpga-development', 'FPGA development', ['FPGA design', 'FPGA implementation']],
      ['physical-design', 'Physical design', []],
      ['formal-verification', 'Formal verification', []],
      ['pcie', 'PCI Express', ['PCIe']],
      ['ethernet', 'Ethernet', []],
      ['tcp-ip', 'TCP/IP', []],
      ['dns', 'Domain Name System', ['DNS']],
      ['bgp', 'Border Gateway Protocol', ['BGP']],
      ['tls', 'Transport Layer Security', ['TLS', 'mTLS']],
      ['rate-limiting', 'Rate limiting', ['rate-limiting']],
      ['nosql', 'NoSQL databases', ['NoSQL']],
      ['saml', 'SAML', ['SAML 2.0']],
      ['sso', 'Single sign-on', ['single sign on', 'SSO']],
      ['scim', 'SCIM', []],
      ['rbac', 'Role-based access control', ['role based access control', 'RBAC']],
      ['abac', 'Attribute-based access control', ['attribute based access control', 'ABAC']],
      ['openapi', 'OpenAPI', []],
      ['websockets', 'WebSockets', ['WebSocket']],
      ['mqtt', 'MQTT', []],
      ['rdma', 'RDMA', ['remote direct memory access']],
      ['nvme', 'NVMe', []],
      ['configuration-management', 'Configuration management', []],
    ],
  },
  {
    kind: 'capability',
    family: 'security',
    entries: [
      ['threat-modeling', 'Threat modeling', ['threat modelling']],
      ['vulnerability-management', 'Vulnerability management', []],
      [
        'identity-access-management',
        'Identity and access management',
        ['identity access management', 'identity management', 'access management'],
      ],
      ['zero-trust', 'Zero trust', ['zero-trust']],
      ['cloud-security', 'Cloud security', []],
      ['application-security', 'Application security', []],
      ['secure-coding', 'Secure coding', []],
      ['cryptography', 'Cryptography', []],
      ['security-operations', 'Security operations', []],
      ['threat-intelligence', 'Threat intelligence', []],
      ['vulnerability-assessment', 'Vulnerability assessment', []],
      ['secrets-management', 'Secrets management', ['secret management']],
    ],
  },
  {
    kind: 'tool',
    family: 'business-tools',
    entries: [
      ['jira', 'Jira', []],
      ['confluence', 'Confluence', []],
      ['sap', 'SAP', []],
      ['netsuite', 'NetSuite', []],
      ['workday', 'Workday', []],
      ['greenhouse', 'Greenhouse', []],
      ['marketo', 'Marketo', []],
      ['zendesk', 'Zendesk', []],
      ['servicenow', 'ServiceNow', []],
      ['google-sheets', 'Google Sheets', []],
      ['powerpoint', 'PowerPoint', ['Microsoft PowerPoint']],
      ['coupa', 'Coupa', []],
      ['anaplan', 'Anaplan', []],
    ],
  },
  {
    kind: 'capability',
    family: 'product-design',
    entries: [
      ['product-management', 'Product management', []],
      ['product-analytics', 'Product analytics', []],
      ['market-research', 'Market research', []],
      ['competitive-analysis', 'Competitive analysis', []],
      [
        'requirements-gathering',
        'Requirements gathering',
        ['requirements elicitation', 'requirement elicitation'],
      ],
      ['usability-testing', 'Usability testing', ['usability tests']],
      ['interaction-design', 'Interaction design', []],
      ['visual-design', 'Visual design', []],
      ['design-systems', 'Design systems', ['design system']],
      ['information-architecture', 'Information architecture', []],
      ['wireframing', 'Wireframing', ['wireframes']],
      ['ui-prototyping', 'UI prototyping', ['interactive prototypes', 'interactive prototyping']],
      ['web-accessibility', 'Web accessibility', ['WCAG', 'accessible interfaces']],
    ],
  },
  {
    kind: 'tool',
    family: 'creative-tools',
    entries: [
      ['photoshop', 'Adobe Photoshop', ['Photoshop']],
      ['illustrator', 'Adobe Illustrator', ['Illustrator']],
      ['blender', 'Blender', []],
      ['maya', 'Autodesk Maya', ['Maya']],
      ['houdini', 'Houdini', []],
      ['unreal-engine', 'Unreal Engine', []],
      ['unity-engine', 'Unity game engine', ['Unity engine', 'Unity3D']],
    ],
  },
  {
    kind: 'capability',
    family: 'sales-marketing',
    entries: [
      ['enterprise-sales', 'Enterprise sales', []],
      ['sales-forecasting', 'Sales forecasting', []],
      ['account-planning', 'Account planning', ['account plans']],
      ['sales-pipeline', 'Sales pipeline management', ['pipeline management']],
      ['territory-planning', 'Territory planning', ['territory management']],
      ['sales-enablement', 'Sales enablement', []],
      ['customer-success', 'Customer success', []],
      ['customer-onboarding', 'Customer onboarding', []],
      ['demand-generation', 'Demand generation', []],
      ['product-marketing', 'Product marketing', []],
      ['growth-marketing', 'Growth marketing', []],
      ['content-marketing', 'Content marketing', []],
      ['email-marketing', 'Email marketing', []],
      ['seo', 'Search engine optimization', ['search engine optimisation', 'SEO']],
      ['marketing-automation', 'Marketing automation', []],
      ['crm', 'Customer relationship management', ['CRM']],
      ['social-media-marketing', 'Social media marketing', []],
    ],
  },
  {
    kind: 'capability',
    family: 'people-finance-operations',
    entries: [
      ['workforce-planning', 'Workforce planning', []],
      ['compensation-planning', 'Compensation planning', []],
      ['benefits-administration', 'Benefits administration', []],
      ['applicant-tracking', 'Applicant tracking systems', ['applicant tracking system']],
      ['succession-planning', 'Succession planning', []],
      ['organizational-design', 'Organizational design', ['organisational design']],
      ['financial-reporting', 'Financial reporting', []],
      ['public-accounting', 'Public accounting', []],
      ['technical-accounting', 'Technical accounting', []],
      ['internal-controls', 'Internal controls', []],
      ['revenue-recognition', 'Revenue recognition', []],
      ['gaap', 'GAAP', ['Generally Accepted Accounting Principles']],
      ['ifrs', 'IFRS', ['International Financial Reporting Standards']],
      ['budgeting', 'Budgeting', []],
      ['procurement', 'Procurement', []],
      ['supply-chain', 'Supply chain management', ['supply chain']],
      ['risk-management', 'Risk management', []],
      ['change-management', 'Change management', []],
      ['project-management', 'Project management', []],
      ['program-management', 'Program management', ['programme management']],
      ['process-improvement', 'Process improvement', ['process improvements']],
    ],
  },
];
