import type { ConceptKind } from './model.js';

// Explicit, curated names. Ambiguous everyday abbreviations are intentionally omitted.
export const engineeringPacks: {
  kind: ConceptKind;
  family: string;
  entries: [string, string, string[]][];
}[] = [
  {
    kind: 'language',
    family: 'backend',
    entries: [
      ['scala', 'Scala', ['Scala']],
      ['c', 'C', ['embedded C', 'C language', 'C programming']],
      ['php', 'PHP', ['PHP']],
    ],
  },
  {
    kind: 'tool',
    family: 'operations',
    entries: [
      ['datadog', 'Datadog', ['Datadog']],
      ['sql-server', 'Microsoft SQL Server', ['Microsoft SQL Server', 'SQL Server']],
      ['claude-code', 'Claude Code', ['Claude Code']],
      ['asio', 'Asio', ['Boost.Asio', 'Asio']],
    ],
  },
  {
    kind: 'capability',
    family: 'backend',
    entries: [
      [
        'high-throughput',
        'High-throughput systems',
        [
          'high-throughput systems',
          'high throughput systems',
          'high-throughput services',
          'high throughput services',
        ],
      ],
      [
        'saas',
        'SaaS platforms',
        ['SaaS', 'SaaS platform', 'SaaS platforms', 'software as a service'],
      ],
      [
        'soa',
        'Service-oriented architecture',
        [
          'service-oriented architecture',
          'service-oriented architectures',
          'service oriented architectures',
          'SOA',
        ],
      ],
      [
        'multi-tenancy',
        'Multi-tenancy',
        ['multi-tenant', 'multi tenant', 'tenant-isolated', 'multi-tenancy'],
      ],
      ['event-sourcing', 'Event sourcing', ['event sourcing', 'event-sourced', 'event sourced']],
      [
        'serialization',
        'Serialization',
        ['serialization', 'serializers', 'binary payload parsing'],
      ],
      ['crash-recovery', 'Crash recovery', ['crash recovery', 'deterministic crash recovery']],
      ['deduplication', 'Deduplication', ['deduplication']],
      ['bounded-retries', 'Bounded retries', ['bounded retries', 'independent retries']],
      ['failure-isolation', 'Failure isolation', ['failure isolation']],
      [
        'transaction-locking',
        'Transaction locking',
        ['row-level SQL locking', 'row-level locking', 'SQL locking'],
      ],
      [
        'animation-pipelines',
        'Animation pipelines',
        ['animation studios', 'animation pipelines', 'animation studio pipelines'],
      ],
    ],
  },
  {
    kind: 'capability',
    family: 'machine-learning',
    entries: [
      [
        'generative-ai',
        'Generative AI',
        ['generative AI', 'GenAI', 'GenAI-native', 'generative artificial intelligence'],
      ],
      [
        'ml-inference',
        'ML inference',
        [
          'ML inference',
          'model inference',
          'inference serving',
          'scalable inference',
          'inference technologies',
        ],
      ],
      [
        'model-training',
        'Model training',
        [
          'model training',
          'training models',
          'training technologies',
          'training and inference technologies',
        ],
      ],
    ],
  },
  {
    kind: 'tool',
    family: 'compiler',
    entries: [
      ['llvm', 'LLVM', ['LLVM']],
      ['clang', 'Clang', ['Clang', 'clang++']],
      ['gcc', 'GCC', ['GCC', 'GNU Compiler Collection']],
      ['msvc', 'MSVC', ['MSVC', 'Microsoft Visual C++']],
      ['clang-tidy', 'clang-tidy', ['clang-tidy']],
      ['lldb', 'LLDB', ['LLDB']],
      ['gdb', 'GDB', ['GDB']],
      ['cmake', 'CMake', ['CMake']],
      ['ninja-build', 'Ninja build', ['Ninja build', 'Ninja build system']],
      ['bazel', 'Bazel', ['Bazel']],
      ['make', 'GNU Make', ['GNU Make', 'Makefile', 'Makefiles']],
      ['address-sanitizer', 'AddressSanitizer', ['AddressSanitizer', 'ASan']],
      ['thread-sanitizer', 'ThreadSanitizer', ['ThreadSanitizer', 'TSan']],
      ['valgrind', 'Valgrind', ['Valgrind']],
      ['perf', 'Linux perf', ['Linux perf']],
      ['mlir', 'MLIR', ['MLIR']],
      ['cuda', 'CUDA', ['CUDA']],
      ['openmp', 'OpenMP', ['OpenMP']],
    ],
  },
  {
    kind: 'capability',
    family: 'systems',
    entries: [
      [
        'compiler-development',
        'Compiler development',
        ['compiler development', 'compiler construction'],
      ],
      [
        'compiler-frontends',
        'Compiler frontends',
        ['compiler frontend', 'compiler front-end', 'compiler frontends'],
      ],
      [
        'compiler-optimization',
        'Compiler optimization',
        [
          'compiler optimization',
          'compiler optimisation',
          'optimization passes',
          'optimisation passes',
        ],
      ],
      [
        'intermediate-representation',
        'Intermediate representations',
        ['intermediate representation', 'LLVM IR'],
      ],
      ['static-analysis', 'Static analysis', ['static analysis', 'static code analysis']],
      ['code-generation', 'Code generation', ['code generation']],
      ['build-systems', 'Build systems', ['build systems', 'build tooling']],
      ['debugging', 'Debugging', ['debugging']],
      ['profiling', 'Profiling', ['profiling', 'CPU profiles', 'flame graphs']],
      ['heap-allocation', 'Heap allocation', ['heap allocation', 'heap allocations']],
      ['stack-allocation', 'Stack allocation', ['stack allocation']],
      ['memory-ownership', 'Memory ownership', ['memory ownership', 'ownership semantics']],
      ['raii', 'RAII', ['RAII', 'resource acquisition is initialization']],
      ['smart-pointers', 'Smart pointers', ['smart pointers', 'unique_ptr', 'shared_ptr']],
      [
        'synchronization',
        'Synchronization',
        ['thread synchronization', 'thread synchronisation', 'lock contention'],
      ],
      [
        'atomic-operations',
        'Atomic operations',
        ['atomic operations', 'atomic instructions', 'std::atomic'],
      ],
      ['race-conditions', 'Race conditions', ['race conditions', 'data races']],
      ['deadlocks', 'Deadlock analysis', ['deadlocks', 'deadlock detection']],
      ['lock-free', 'Lock-free programming', ['lock-free', 'lock free programming']],
      ['thread-pools', 'Thread pools', ['thread pools', 'thread pool']],
      [
        'async-programming',
        'Asynchronous programming',
        ['asynchronous programming', 'async/await'],
      ],
      ['simd', 'SIMD', ['SIMD', 'vectorized instructions', 'vectorised instructions']],
      ['cpu-cache', 'CPU cache behavior', ['CPU cache', 'cache locality', 'cache coherence']],
      [
        'throughput',
        'Throughput optimization',
        ['throughput optimization', 'throughput optimisation'],
      ],
      ['latency-analysis', 'Latency analysis', ['latency analysis', 'p99 latency', 'p95 latency']],
      ['garbage-collection', 'Garbage collection', ['garbage collection']],
      ['gpu-programming', 'GPU programming', ['GPU programming', 'GPU kernels']],
    ],
  },
  {
    kind: 'capability',
    family: 'distributed',
    entries: [
      ['replication', 'Replication', ['data replication', 'database replication']],
      ['sharding', 'Sharding', ['sharding', 'database shards']],
      ['partitioning', 'Data partitioning', ['data partitioning', 'database partitioning']],
      ['consensus', 'Distributed consensus', ['distributed consensus', 'Raft', 'Paxos']],
      ['failover', 'Failover', ['failover', 'fail-over']],
      ['circuit-breakers', 'Circuit breakers', ['circuit breakers', 'circuit breaker']],
      ['retry-policies', 'Retry policies', ['retry policies', 'exponential backoff']],
      ['idempotency', 'Idempotency', ['idempotency', 'idempotent']],
      ['eventual-consistency', 'Eventual consistency', ['eventual consistency']],
      ['strong-consistency', 'Strong consistency', ['strong consistency', 'linearizability']],
      ['load-balancing', 'Load balancing', ['load balancing', 'load balancers']],
      ['service-discovery', 'Service discovery', ['service discovery']],
      ['message-queues', 'Message queues', ['message queues', 'message queue']],
      [
        'event-driven',
        'Event-driven architecture',
        ['event-driven architecture', 'event driven architecture'],
      ],
      ['stream-processing', 'Stream processing', ['stream processing', 'streaming pipelines']],
      ['batch-processing', 'Batch processing', ['batch processing']],
      ['backpressure', 'Backpressure', ['backpressure', 'back-pressure']],
      ['disaster-recovery', 'Disaster recovery', ['disaster recovery']],
      ['multi-region', 'Multi-region systems', ['multi-region', 'multi region deployment']],
      ['distributed-tracing', 'Distributed tracing', ['distributed tracing']],
      ['control-planes', 'Control planes', ['control planes', 'control plane']],
    ],
  },
  {
    kind: 'tool',
    family: 'backend',
    entries: [
      ['elasticsearch', 'Elasticsearch', ['Elasticsearch']],
      ['opensearch', 'OpenSearch', ['OpenSearch']],
      ['sqlite', 'SQLite', ['SQLite']],
      ['cassandra', 'Apache Cassandra', ['Apache Cassandra', 'Cassandra']],
      ['clickhouse', 'ClickHouse', ['ClickHouse']],
      ['flink', 'Apache Flink', ['Apache Flink', 'Flink']],
      ['airflow', 'Apache Airflow', ['Apache Airflow', 'Airflow']],
      ['prometheus', 'Prometheus', ['Prometheus']],
      ['grafana', 'Grafana', ['Grafana']],
      ['opentelemetry', 'OpenTelemetry', ['OpenTelemetry']],
      ['nginx', 'NGINX', ['NGINX']],
      ['envoy', 'Envoy proxy', ['Envoy proxy']],
      ['ansible', 'Ansible', ['Ansible']],
      ['helm', 'Helm', ['Helm']],
      ['pulumi', 'Pulumi', ['Pulumi']],
      ['jenkins', 'Jenkins', ['Jenkins']],
      ['github-actions', 'GitHub Actions', ['GitHub Actions']],
      ['gitlab-ci', 'GitLab CI', ['GitLab CI', 'GitLab CI/CD']],
      ['argo-cd', 'Argo CD', ['Argo CD', 'ArgoCD']],
    ],
  },
  {
    kind: 'platform',
    family: 'cloud',
    entries: [
      ['aws-ec2', 'Amazon EC2', ['Amazon EC2', 'AWS EC2']],
      ['aws-s3', 'Amazon S3', ['Amazon S3', 'AWS S3']],
      ['aws-ecs', 'Amazon ECS', ['Amazon ECS', 'AWS ECS']],
      ['aws-elasticache', 'Amazon ElastiCache', ['Amazon ElastiCache', 'AWS ElastiCache']],
      ['aws-lambda', 'AWS Lambda', ['AWS Lambda']],
      ['aws-eks', 'Amazon EKS', ['Amazon EKS', 'AWS EKS']],
      ['aws-sqs', 'Amazon SQS', ['Amazon SQS', 'AWS SQS']],
      ['aws-rds', 'Amazon RDS', ['Amazon RDS', 'AWS RDS']],
      ['azure-aks', 'Azure Kubernetes Service', ['Azure Kubernetes Service', 'Azure AKS']],
      ['azure-functions', 'Azure Functions', ['Azure Functions']],
      ['gcp-gke', 'Google Kubernetes Engine', ['Google Kubernetes Engine', 'GKE']],
      ['gcp-bigquery', 'BigQuery', ['BigQuery']],
      ['gcp-pubsub', 'Google Pub/Sub', ['Google Pub/Sub', 'Cloud Pub/Sub']],
    ],
  },
  {
    kind: 'capability',
    family: 'backend',
    entries: [
      ['api-design', 'API design', ['API design', 'API versioning']],
      ['oauth', 'OAuth', ['OAuth', 'OAuth2', 'OAuth 2.0']],
      ['oidc', 'OpenID Connect', ['OpenID Connect', 'OIDC']],
      ['authentication', 'Authentication', ['authentication']],
      ['authorization', 'Authorization', ['authorization', 'authorisation']],
      [
        'database-transactions',
        'Database transactions',
        ['database transactions', 'ACID transactions'],
      ],
      ['database-indexing', 'Database indexing', ['database indexing', 'database indexes']],
      ['query-optimization', 'Query optimization', ['query optimization', 'query optimisation']],
      ['schema-design', 'Schema design', ['schema design', 'data modeling', 'data modelling']],
      ['integration-testing', 'Integration testing', ['integration testing', 'integration tests']],
      ['unit-testing', 'Unit testing', ['unit testing', 'unit tests']],
      ['load-testing', 'Load testing', ['load testing', 'load tests']],
      ['security-testing', 'Security testing', ['security testing', 'penetration testing']],
      [
        'slo',
        'Service-level objectives',
        ['service-level objectives', 'service level objectives', 'SLOs'],
      ],
      ['incident-response', 'Incident response', ['incident response', 'on-call rotation']],
      ['capacity-planning', 'Capacity planning', ['capacity planning']],
      ['canary-deployments', 'Canary deployments', ['canary deployments', 'canary releases']],
      [
        'blue-green',
        'Blue-green deployments',
        ['blue-green deployments', 'blue green deployments'],
      ],
      ['feature-flags', 'Feature flags', ['feature flags', 'feature toggles']],
      [
        'architecture-design',
        'Architecture design',
        ['architecture design', 'system design', 'architectural decisions'],
      ],
      ['etl', 'ETL pipelines', ['ETL', 'ELT pipelines']],
      ['data-quality', 'Data quality', ['data quality']],
      ['data-governance', 'Data governance', ['data governance']],
      ['feature-engineering', 'Feature engineering', ['feature engineering']],
      ['model-evaluation', 'Model evaluation', ['model evaluation']],
    ],
  },
  {
    kind: 'competency',
    family: 'delivery',
    entries: [
      [
        'cross-functional-delivery',
        'Cross-functional delivery',
        ['cross-functional delivery', 'cross functional delivery'],
      ],
      ['technical-direction', 'Technical direction', ['technical direction', 'technical strategy']],
      ['hiring', 'Hiring', ['hiring engineers', 'interviewing candidates']],
      [
        'performance-reviews',
        'People performance reviews',
        ['performance reviews', 'performance appraisals'],
      ],
    ],
  },
];
