// Fictional, manually labeled regression examples; not a held-out accuracy benchmark.
export const activityCases: [string, string][] = [
  ['Implemented automatic failover between replicas', 'fault-tolerance'],
  ['Designed automatic failover', 'failover'],
  ['Kept services running when individual machines failed', 'high-availability'],
  ['Keep services running if servers fail', 'fault-tolerance'],
  ['Cut p99 request time', 'low-latency'],
  ['Reduced response latency', 'performance-optimization'],
  ['Profiled lock contention', 'profiling'],
  ['Profiled CPU bottlenecks', 'performance-optimization'],
  ['Delivered changes spanning engineering, product and operations', 'cross-functional-delivery'],
  ['Delivered projects across multiple teams', 'cross-functional-delivery'],
  ['Owned initiatives across teams', 'cross-functional-leadership'],
  ['Led technical initiatives across multiple teams', 'cross-functional-leadership'],
  ['Set technical direction', 'technical-direction'],
  ['Established the technical direction', 'technical-direction'],
  ['Managed a team of engineers', 'leadership'],
  ['Supervised engineers', 'leadership'],
  ['Mentored junior developers', 'mentoring'],
  ['Led cross-functional initiatives', 'cross-functional-leadership'],
  ['Wrote custom LLVM optimization passes', 'llvm'],
  ['Extended the Clang frontend', 'clang'],
  ['Restored services after node failures', 'fault-tolerance'],
  ['Processed many requests in parallel', 'concurrency'],
  ['Optimized SQL queries', 'query-optimization'],
  ['Rolled out releases gradually', 'canary-deployments'],
  ['Built services using AWS EC2', 'aws-ec2'],
  ['Built code using RAII and smart pointers', 'raii'],
];

export const unrelatedCases: [string, string][] = [
  ['Improved team performance', 'performance-optimization'],
  ['Worked with big teams', 'distributed-systems'],
  ['Lead generation and sales targets', 'leadership'],
  ['I react to feedback', 'react'],
  ['I go to conferences', 'golang'],
  ['A low level of responsibility', 'low-level'],
  ['Building customer relationships', 'distributed-systems'],
  ['High availability of interview slots', 'failover'],
  ['Hiring a compiler developer', 'llvm'],
  ['Used Redis', 'aws'],
  ['Used C++', 'clang'],
  ['Used Clang', 'compiler-frontends'],
  ['Used clang-tidy', 'clang'],
  ['Read LLVM IR', 'llvm'],
  ['A spark of creativity', 'spark'],
  ['Sales growth at scale', 'distributed-systems'],
  ['Aligned product plans', 'leadership'],
  ['Attended a team meeting', 'cross-functional-leadership'],
  ['Contact: python@example.invalid', 'python'],
  ['Employer: Azure', 'azure'],
];
