export const categories = [
  { slug: 'engineering', name: 'Engineering' },
  { slug: 'data-ai', name: 'Data & AI' },
  { slug: 'research', name: 'Research' },
  { slug: 'quant-trading', name: 'Quantitative Research & Trading' },
  { slug: 'product', name: 'Product' },
  { slug: 'design', name: 'Design' },
  { slug: 'sales', name: 'Sales & Business Development' },
  { slug: 'marketing', name: 'Marketing & Communications' },
  { slug: 'customer-success', name: 'Customer Success & Support' },
  { slug: 'people', name: 'Human Resources & Recruiting' },
  { slug: 'finance', name: 'Finance & Accounting' },
  { slug: 'legal', name: 'Legal, Compliance & Policy' },
  { slug: 'security-it', name: 'Security & IT' },
  { slug: 'operations', name: 'Operations & Administration' },
  { slug: 'manufacturing', name: 'Manufacturing & Supply Chain' },
  { slug: 'retail', name: 'Retail & Field Services' },
  { slug: 'creative', name: 'Creative & Content' },
  { slug: 'unclassified', name: 'Other / Unclassified' },
] as const;
